name: Integration Test


on:
  pull_request: 
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true
        job-status: success
    - name: Run mvn install
      run: |
        mvn install -DskipTests

    - name: Zip the file
      run: |
        zip -r assignment2.zip ./
        ls -lrth


    - name: Init Packer
      run: packer init -upgrade packer/my-ami.pkr.hcl

    - name: Build AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: packer build 'packer/my-ami.pkr.hcl'


      
      




